using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class Bullet : MonoBehaviour
{
    public GameObject effect;            // Genel mermi efekti
    public GameObject explosionEffect;   // Enemy'ye Áarpżnca Ųzel patlama efekti

    PlayerController control;

    void Start()
    {
        control = GameObject.Find("Player").GetComponent<PlayerController>();
    }

    private void OnCollisionEnter(Collision collision)
    {
        // Her ÁarpżĢmada normal efekt oynat
        Instantiate(effect, transform.position, transform.rotation);

        if (collision.gameObject.CompareTag("Enemy"))
        {
            // DŁĢmana Ųzel patlama efekti
            Instantiate(explosionEffect, transform.position, transform.rotation);

            // Skoru arttżr
            control.score++;

            // DŁĢmanż yok et
            Destroy(collision.gameObject);
        }

        // Mermiyi her durumda yok et
        Destroy(gameObject);
    }
}
