using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
[RequireComponent(typeof(CharacterController))]

public class PlayerController : MonoBehaviour
{ 
    public float moveSpeed = 5f; // Tankïŋ―n ileri/geri hareket hïŋ―zïŋ―
    public float rotationSpeed = 50f; // Tankïŋ―n dïŋ―nïŋ―ïŋ― hïŋ―zïŋ―

    private Rigidbody tankRigidbody;
    public TMP_Text timeText;
    public float time = 60f;
    public TMP_Text scoreText, lastText;
    public int score = 0;
    public GameObject lastPanel;
    private void Awake()
    {
        // Tankïŋ―n RigidBody bileïŋ―enini alïŋ―yoruz
        tankRigidbody = GetComponent<Rigidbody>();
    }
    private void Update()
    {
        scoreText.text = "Score: " + score;
        // Hareket ve dïŋ―nïŋ―ïŋ― fonksiyonlarïŋ―nïŋ― ïŋ―aïŋ―ïŋ―rïŋ―yoruz
        if (time > 1)
        {
            lastPanel.SetActive(false);
            time -= Time.deltaTime;
            int timeInteger = Mathf.FloorToInt(time);
            timeText.text = "Time: " + timeInteger.ToString();
            Move();
            Rotate();
        }
        else
        {
            lastText.text = "Your Score: " + score;
            lastPanel.SetActive(true);
            Time.timeScale = 0f;
        }
    }
    private void Move()
    {
        // ïŋ―leri/geri hareket iïŋ―in input deïŋ―erini alïŋ―yoruz
        float moveInput = Input.GetAxis("Vertical");
        // Hareket yïŋ―nïŋ―nïŋ― belirliyoruz
        Vector3 moveDirection = transform.forward * moveInput;
        // Hareket yïŋ―nïŋ―nïŋ― RigidBody ïŋ―zerinden uyguluyoruz
        tankRigidbody.linearVelocity = moveDirection * moveSpeed;
    }
    private void Rotate()
    {
        // Tankïŋ―n dïŋ―nïŋ―ïŋ―ïŋ― iïŋ―in input deïŋ―erini alïŋ―yoruz
        float rotateInput = Input.GetAxis("Horizontal");
        // Dïŋ―nïŋ―ïŋ― yïŋ―nïŋ―nïŋ― belirliyoruz
        float rotationAmount = rotateInput * rotationSpeed * Time.fixedDeltaTime;
        // Yeni rotasyonu hesaplïŋ―yoruz
        Quaternion rotation = Quaternion.Euler(0f, rotationAmount, 0f);
        // Tankïŋ― dïŋ―ndïŋ―rïŋ―yoruz
        tankRigidbody.MoveRotation(tankRigidbody.rotation * rotation);
    }
}


